name: OpenShift 

env: 
  APP_NAME: parksmap-web
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: "demo"

  APP_PORT: "8080"

on:
  push: 
    branches: [ master ]

jobs:
  build-and-push: 
    name: Build and push to github container registry
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    -   name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

    -   name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./parksmap-web
          push: true
          tags: iyzyman/dev:latest
